import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import NavPage from '@/app/_components/nav/page'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
          antialiased bg-gradient-to-r 
          from-blue-500 to-purple-400
          relative
          min-h-screen
          pb-4
        `}
      >
        <NavPage />
        {children}
      </body>
    </html>
  )
}
